#include "aim-flex.hpp"

CEngineClient* engineclient;
CEngineVGui* enginevgui;
CMatSystemSurface* matsystemsurface;
IClientEntityList* entitylist;
CHLClient* client;
ICVar* cvar;
IVModelInfo* modelinfo;
CGameMovement* gamemovement;
IPrediction* prediction;
IEngineTrace* enginetrace;
IGameEventManager2* eventmanager;
IMaterialSystem* materialsystem;
IVRenderView* renderview;
IVModelRender* modelrender;
IPhysicsSurfaceProps* physprops;
ClientModeShared* clientmode;
CGlobalVarsBase* globals;
CInput* cmdinput;
CClientState* cl;
IMemAlloc* g_pMemAlloc;
